export { authApi } from "./auth";
export { workoutsApi, type AddWorkoutInput } from "./workouts";
export { profileApi } from "./profile";
export { bodyweightApi, type BodyweightRecord } from "./bodyweight";
export { analyticsApi } from "./analytics";
export { restDaysApi, type RestDayData } from "./rest-days";
export { heatmapApi, type HeatmapDay } from "./heatmap";
export { nutritionApi } from "./nutrition";
export { waterApi } from "./water";
export { foodCatalogApi, type CatalogSyncResult } from "./food-catalog";
export { historyApi, type HistoryDate } from "./history";
export { coachApi } from "./coach";
